=== prateekt/troyspace/xml_schemas/calendar_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.7.0 (http://www.liquid-technologies.com) -->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="calendar">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="year">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="month">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="day">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="100000" name="event">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" type="xs:string" />
                                <xs:element name="start_time">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="hour" type="xs:string" />
                                      <xs:element name="minute" type="xs:string" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="end_time">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="hour" type="xs:string" />
                                      <xs:element name="minute" type="xs:string" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="location" type="xs:string" />
                                <xs:element name="description" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="day_name" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="month_name" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="year_name" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== prateekt/troyspace/xml_schemas/event_exa_file.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.7.0 (http://www.liquid-technologies.com) -->
<calendar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Documents%20and%20Settings/Prateek%20Tandon/Desktop/troyspace/xml_schemas/calendar_schema.xsd">
  <year>
    <month>
      <day>
        <event>
          <name>string</name>
          <start_time>
            <hour>string</hour>
            <minute>string</minute>
          </start_time>
          <end_time>
            <hour>string</hour>
            <minute>string</minute>
          </end_time>
          <location>string</location>
          <description>string</description>
        </event>
        <event>
          <name>string</name>
          <start_time>
            <hour>string</hour>
            <minute>string</minute>
          </start_time>
          <end_time>
            <hour>string</hour>
            <minute>string</minute>
          </end_time>
          <location>string</location>
          <description>string</description>
        </event>
        <event>
          <name>string</name>
          <start_time>
            <hour>string</hour>
            <minute>string</minute>
          </start_time>
          <end_time>
            <hour>string</hour>
            <minute>string</minute>
          </end_time>
          <location>string</location>
          <description>string</description>
        </event>
        <event>
          <name>string</name>
          <start_time>
            <hour>string</hour>
            <minute>string</minute>
          </start_time>
          <end_time>
            <hour>string</hour>
            <minute>string</minute>
          </end_time>
          <location>string</location>
          <description>string</description>
        </event>
        <event>
          <name>string</name>
          <start_time>
            <hour>string</hour>
            <minute>string</minute>
          </start_time>
          <end_time>
            <hour>string</hour>
            <minute>string</minute>
          </end_time>
          <location>string</location>
          <description>string</description>
        </event>
        <day_name>string</day_name>
      </day>
      <month_name>string</month_name>
    </month>
    <year_name>string</year_name>
  </year>
</calendar>
